// Module included in the following assemblies:
//
// * machine_management/control_plane_machine_management/cpmso-managing-machines.adoc

ifeval::["{context}" == "control-plane"]
:ROSA:
endif::[]

:_mod-docs-content-type: CONCEPT
[id="cpmso-feat-auto-update_{context}"]
= Automatic updates to the control plane configuration
//Not for ROSA:
ifndef::ROSA[]
The `RollingUpdate` update strategy automatically propagates changes to your control plane configuration.
This update strategy is the default configuration for the control plane machine set.
endif::ROSA[]
//For ROSA:
ifdef::ROSA[]
On ROSA clusters, the control plane machine set automatically propagates changes to your control plane configuration.
The Control Plane Machine Set Operator creates a replacement control plane machine with the configuration that is specified in the CR.
endif::ROSA[]
//Not for ROSA:
ifndef::ROSA[]
For clusters that use the `RollingUpdate` update strategy, the Operator creates a replacement control plane machine with the configuration that is specified in the CR.
endif::ROSA[]
//Anything not enclosed in an ifdef or ifndef prints for everyone:
When the replacement control plane machine is ready, the Operator deletes the control plane machine that is marked for replacement.
The replacement machine then joins the control plane.

If multiple control plane machines are marked for replacement, the Operator protects etcd health during replacement by repeating this replacement process one machine at a time until it has replaced each machine.

ifeval::["{context}" == "control-plane"]
:!ROSA:
endif::[]